name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 12.x
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/eventfully s3://eventfully.se --delete

      - name: Invalidate index.html
        run: aws cloudfront create-invalidation --distribution-id E38RH3DU7HYOIP --paths /index.html
